### ISSUE TITLE
hot reload not working

### ISSUE THREAD

**Issue by krzysztofpniak** [f-f/purescript-react-basic-todomvc#5]
steps to reproduce:
- yarn install
- yarn build
- yarn start
- open App.purs
- change "todos" to "todos 2", save file
- nothing recompiles

**Comment by f-f** [comment]
Hi @krzysztofpniak! The autoreload in `yarn start` is for JS files only.

For autoreloading on changes to `.purs` files you have two options:
- use an editor integration - this will run `purs ide` and recompile the files as you edit them
- run `spago build --watch` in another terminal

I clarified the README to contain the above paragraph

**Comment by krzysztofpniak** [comment]
I'm new to purescript. Thanks for clarification.

**Comment by f-f** [comment]
You're welcome 🙂

**Comment by krzysztofpniak** [comment]
I think it can be simplified by adding `concurrently` as devDependency and modifying start script like this:
`"start": "concurrently \"spago build --watch \" \"parcel index.html\""`

**Comment by f-f** [comment]
Yeah I thought about it, but as mentioned in the readme in the FFI reload case you'd want to restart the JS build only.
But I'd accept a PR if you think it's a better idea! 🙂
